apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt-staging"
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "arthuracs18@gmail.com"
    privateKeySecretRef:
      name: "reveal-ops"
    solvers:
      - http01:
          ingress:
            class: nginx