apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9555
      targetPort: 9555
      protocol: TCP
      name: {{ .Release.Name }}
  selector:
    app: {{ .Release.Name }}
