version: "3"

dotenv: ['.env']

includes:
  tf:
    taskfile: ./cmd/Taskfile-terraform.yml
    dotenv: ['.env']

tasks:
  env:set:
    desc: Set environment
    cmds:
      - |
        echo "Type the environment name:"
        read ENV;
        echo "ENV=$ENV" >> .envfile
        echo "Type the region name:"
        read REGION;
        echo "REGION=$REGION" >> .envfile
        echo "Type the Project name:"
        read PROJECT;
        echo "PROJECT=$PROJECT" >> .envfile
        unset AWS_VAULT
        aws-vault exec $PROJECT-$ENV --region $REGION --no-session
    silent: true

