version: "3"

dotenv: ['.env']

includes:
  tf:
    taskfile: ./cmd/Taskfile-terraform.yml
    dotenv: ['.env']

tasks:
  env:set:
    desc: Set environment
    cmds:
      - |
        echo "Type the environment name:"
        read ENV;
        echo "ENV=$ENV" >> .envfile
        echo "Type the region name:"
        read REGION;
        echo "REGION=$REGION" >> .envfile
        echo "Type the Project name:"
        read PROJECT;
        echo "PROJECT=$PROJECT" >> .envfile
        unset AWS_VAULT
        aws-vault exec $PROJECT-$ENV --region $REGION --no-session
    silent: true

  env:install:
    desc: Download and install tools
    cmds:
      - |
        echo "install terraform? [yes/no]:"
        read TERRAFORM;
        echo "TERRAFORM=$TERRAFORM" > .temp
        echo "install tfenv? [yes/no]:"
        read TF_ENV;
        echo "TF_ENV=$TF_ENV" >> .temp
        echo "install kubectl?: [yes/no]"
        read KUBECTL;
        echo "KUBECTL=$KUBECTL" >> .temp
        echo "install aws-cli?: [yes/no]"
        read AWS_CLI;
        echo "AWS_CLI=$AWS_CLI" >> .temp
        echo "install aws-vault?: [yes/no]"
        read AWS_VAULT;
        echo "AWS_VAULT=AWS_VAULT" >> .temp

    silent: true
