apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-service-deployment
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  selector:
    matchLabels:
      app: deployment-monolith-service
  progressDeadlineSeconds: 600
  replicas: {{.Values.application.replicaCount}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-monolith-service
      {{- if .Values.global.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      progressDeadlineSeconds: 1200 
      {{- if or .Values.global.imagePullSecrets .Values.global.ecr.enabled }}
      imagePullSecrets:
        {{- if .Values.global.ecr.enabled }}
        - name: {{ .Values.global.ecr.secret }}
        {{- end }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.application.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .Values.application.name }}
          image: {{ .Values.application.image }}:{{ .Values.application.tag }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-monolith-volume
              mountPath: C:\\inetpub\\wwwroot\\
          {{- if .Values.application.resources }}
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
          {{- else }}
          # Default resource requests/limits
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          {{- end }}

      volumes:
        - name: config-monolith-volume
          configMap:
            name: {{ .Values.configMap.name }}
            items:
              - key: "Test.config"
                path: "Test.config"