apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
data: 
  Web.config: |
    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <configSections>
        <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
      <sectionGroup name="nwebsec">
          <section name="httpHeaderSecurityModule" type="NWebsec.Modules.Configuration.HttpHeaderSecurityConfigurationSection, NWebsec" requirePermission="false" />
        </sectionGroup></configSections>
      <connectionStrings>
        <add name="DefaultConnection" connectionString="{{ .Values.configMap.DefaultConnectionString }}" providerName="System.Data.SqlClient" />
        <add name="CaseCustodianDataSourceContext" connectionString="{{ .Values.configMap.CaseCustodianDataSourceContextConnectionString }}" providerName="System.Data.EntityClient" />
        <add name="MasterEntities" connectionString="{{ .Values.configMap.MasterEntitiesConnectionString }}" providerName="System.Data.EntityClient" />
        <add name="ProcessingEngineEntities" connectionString="{{ .Values.configMap.ProcessingEngineEntitiesConnectionString }}" providerName="System.Data.EntityClient" />
        <add name="ReportManagementEntities" connectionString="{{ .Values.configMap.ReportManagementEntitiesConnectionString }}" providerName="System.Data.EntityClient" />
        <add name="EntityDb" connectionString="{{ .Values.configMap.EntityDbConnectionString }}" providerName="System.Data.EntityClient" />
        <add name="StagingEntities" connectionString="{{ .Values.configMap.StagingEntitiesConnectionString }}" providerName="System.Data.EntityClient" />
      </connectionStrings>
      <appSettings>
        <add key="FileRepositoryLocation" value="{{ .Values.configMap.FileRepositoryLocation }}" />
        <add key="EmployeeImportTemplateLocation" value="{{ .Values.configMap.EmployeeImportTemplateLocation }}" />
        <add key="NonLegalHelpDocumentName" value="{{ .Values.configMap.NonLegalHelpDocumentName }}" />
        <add key="EncyKey" value="{{ .Values.configMap.EncyKey }}" />
        <add key="DocumentStoreLocation" value="{{ .Values.configMap.DocumentStoreLocation }}" />
        <add key="documentStore_path" value="{{ .Values.configMap.documentStore_path }}" />
        <add key="document_physical_path" value="{{ .Values.configMap.document_physical_path }}" />
        <add key="WebUrl" value="{{ .Values.configMap.WebUrl }}" />
        <add key="StaticUrl" value="{{ .Values.configMap.StaticUrl }}" />
        <add key="LHExpiryTimeInHours" value="{{ .Values.configMap.LHExpiryTimeInHours }}" />
        <add key="redis-cache" value="{{ .Values.configMap.redisCache }}" />
        <add key="Log4NetConfigPath" value="{{ .Values.configMap.Log4NetConfigPath }}" />
        <add key="EventLogName" value="{{ .Values.configMap.EventLogName }}" />
        <add key="EventLogSource" value="{{ .Values.configMap.EventLogSource }}" />
        <add key="IsAsyncLoggingEnabled" value="{{ .Values.configMap.IsAsyncLoggingEnabled }}" />
        <add key="PrivateKey" value="{{ .Values.configMap.PrivateKey }}" />
        <add key="DefaultPasswordKey" value="{{ .Values.configMap.DefaultPasswordKey }}" />
        <add key="AccessTokenExpiryInMinutes" value="{{ .Values.configMap.AccessTokenExpiryInMinutes }}" />
        <add key="AccessControlAllowOrigin" value="{{ .Values.configMap.AccessControlAllowOrigin }}" />
        <add key="PluginUserFullName" value="{{ .Values.configMap.PluginUserFullName }}" />
        <add key="ImportRowsThreshold" value="{{ .Values.configMap.ImportRowsThreshold }}" />
        <add key="AllowedFileTypesForImport" value="{{ .Values.configMap.AllowedFileTypesForImport }}" />
        <add key="PublishStackTrace" value="{{ .Values.configMap.PublishStackTrace }}" />
        <add key="ClientInstance" value="{{ .Values.configMap.ClientInstance }}" />
        <add key="ClientDoamins" value="{{ .Values.configMap.ClientDoamins }}" />
        <add key="aspnet:UseTaskFriendlySynchronizationContext" value="{{ .Values.configMap.useTaskFriendlySynchronizationContext }}" />
        <add key="ForgotPwdExpiryTimeInHours" value="{{ .Values.configMap.ForgotPwdExpiryTimeInHours }}" />
        <add key="Issuer" value="{{ .Values.configMap.Issuer }}" />
        <add key="Audience" value="{{ .Values.configMap.Audience }}" />
        <add key="Secret" value="{{ .Values.configMap.Secret }}" />
        <add key="IsAngularMigrated" value="{{ .Values.configMap.IsAngularMigrated }}" />
        <add key="CCDInsertChunk" value="{{ .Values.configMap.CCDInsertChunk }}" />
        <add key="MaximumCCDInsertions" value="{{ .Values.configMap.MaximumCCDInsertions }}" />
        <add key="ClientAppConfigDecryptKey" value="{{ .Values.configMap.ClientAppConfigDecryptKey }}" />
        <add key="UIUrl" value="{{ .Values.configMap.UIUrl }}" />
        <add key="AntiVirusCheckerClamAV" value="{{ .Values.configMap.AntiVirusCheckerClamAV }}" />
      </appSettings>
      <!--
        For a description of web.config changes see http://go.microsoft.com/fwlink/?LinkId=235367.

        The following attributes can be set on the <httpRuntime> tag.
          <system.Web>
            <httpRuntime targetFramework="4.6.2" />
          </system.Web>
      -->
      <system.web>
        <authentication mode="None" />
        <compilation debug="true" targetFramework="4.8" />
        <httpRuntime targetFramework="4.5.2" maxQueryStringLength="32768" maxUrlLength="65536" executionTimeout="240" maxRequestLength="25600" enableVersionHeader="false" />
        <customErrors mode="RemoteOnly" />
      </system.web>
      <system.webServer>
        <httpProtocol>
          <customHeaders>
            <remove name="X-Powered-By" />
          <clear /></customHeaders>
        </httpProtocol>
        <modules>
          <remove name="FormsAuthentication" />
        <add name="NWebsecHttpHeaderSecurityModule" type="NWebsec.Modules.HttpHeaderSecurityModule, NWebsec" /></modules>
        <handlers>
          <remove name="ExtensionlessUrl-Integrated-4.0" />
          <add name="ExtensionlessUrl-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,DELETE,PUT,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
        <remove name="ExtensionlessUrlHandler-Integrated-4.0" /><remove name="OPTIONSVerbHandler" /><remove name="TRACEVerbHandler" /><add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" /></handlers>
        <security>
          <requestFiltering>
            <requestLimits maxQueryString="32768" maxAllowedContentLength="26214400" />
          <hiddenSegments>
              <add segment="NWebsecConfig" />
            </hiddenSegments></requestFiltering>
        </security>
      </system.webServer>
      <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Owin.Security" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="0.0.0.0-4.2.2.0" newVersion="4.2.2.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Owin.Security.OAuth" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="0.0.0.0-4.2.2.0" newVersion="4.2.2.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Owin.Security.Cookies" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="0.0.0.0-4.2.2.0" newVersion="4.2.2.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="0.0.0.0-4.2.2.0" newVersion="4.2.2.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" />
            <bindingRedirect oldVersion="0.0.0.0-13.0.0.0" newVersion="13.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Web.Optimization" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="1.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="0.0.0.0-1.6.5135.21930" newVersion="1.6.5135.21930" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.2.9.0" newVersion="5.2.9.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.2.9.0" newVersion="5.2.9.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Antlr3.Runtime" publicKeyToken="eb42632606e9261f" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-3.5.0.2" newVersion="3.5.0.2" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Web.Cors" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.2.9.0" newVersion="5.2.9.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Xml.ReaderWriter" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Extensions.DependencyInjection" publicKeyToken="adb9793829ddae60" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.2" newVersion="7.0.0.2" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.IdentityModel.Tokens" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-6.32.1.0" newVersion="6.32.1.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-6.32.1.0" newVersion="6.32.1.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.8.4.0" newVersion="5.8.4.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Data.OData" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.8.4.0" newVersion="5.8.4.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Spatial" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.8.4.0" newVersion="5.8.4.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Reflection.TypeExtensions" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="1.0.0.0-5.2.9.0" newVersion="5.2.9.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Azure.KeyVault.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-3.0.5.0" newVersion="3.0.5.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Web.Infrastructure" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Security.Cryptography.Pkcs" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.3" newVersion="7.0.0.3" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.0.1.2" newVersion="4.0.1.2" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Text.Encodings.Web" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.0.5.1" newVersion="4.0.5.1" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Bcl.AsyncInterfaces" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.OData.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.17.0.0" newVersion="7.17.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.OData.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.17.0.0" newVersion="7.17.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Spatial" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.17.0.0" newVersion="7.17.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Unity.Abstractions" publicKeyToken="489b6accfaf20ef0" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-5.11.7.0" newVersion="5.11.7.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Extensions.Logging.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.1" newVersion="7.0.0.1" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Text.Json" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.3" newVersion="7.0.0.3" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Extensions.Options" publicKeyToken="adb9793829ddae60" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.1" newVersion="7.0.0.1" />
          </dependentAssembly>
        </assemblyBinding>
      </runtime>
      <entityFramework>
        <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework" />
        <providers>
          <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
        </providers>
        <interceptors>
          <interceptor type="Vertical.Business.Authorization.Interceptors.AuthorizationTreeInterceptor,Vertical.Business" />
          <interceptor type="Vertical.Business.Authorization.Interceptors.AuthorizationCommandInterceptor,Vertical.Business" />
        </interceptors>
      </entityFramework>
      <nwebsec>
        <httpHeaderSecurityModule xmlns="http://nwebsec.com/HttpHeaderSecurityModuleConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NWebsecConfig/HttpHeaderSecurityModuleConfig.xsd">
          <securityHttpHeaders>
            <x-Frame-Options policy="Deny" />
            <x-Content-Type-Options enabled="true" />
            <x-XSS-Protection policy="FilterEnabled" blockMode="true" />
          </securityHttpHeaders>
        </httpHeaderSecurityModule>
      </nwebsec>
    </configuration>
  
