apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "cert-manager"
  namespace: "cert-manager-system"
spec:
  destination:
    name: "cert-manager"
    namespace: "cert-manager-system"
    server: 'https://kubernetes.default.svc'
  source:
    path: "dev/us-east-1/services/system/cert-manager"
    repoURL: 'git@github.com:ArthurMaverick/devops_project.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: devops
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2