{{- if .Values.secrets.enabled }}
{{- if eq  .Values.secrets.provider "external-secrets" }}
{{- if eq  .Values.secrets.externalSecrets.provider "aws" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secrets.externalSecrets.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secrets.externalSecrets.serviceAccount.arn }}
{{ end }}
{{ end }}
{{ end }}