apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  
spec:
  selector:
    app: deployment-hosting-service
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80