apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.repositories.infra.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ .Values.repositories.infra.url }}
  sshPrivateKey: |
    {{ .Values.repositories.infra.sshPrivateKeySecret }}
  insecure: "true"
  enableLfs: "true"