adminPassword: admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - access: proxy
        isDefault: true
        name: prometheus
        type: prometheus
        url: http://prometheus-server.prometheus-system.svc.cluster.local
persistence:
  enabled: true
  storageClassName: gp2
service:
  type: ClusterIP