---
global:
  # K8s namespace. The name of the deployment.
  namespace: "monolith-service"


  ecr:
    enabled: false
    secret: "reveal-ecr"
    # -- AWS Account ID (default "475250404638")
    account: ""
    # -- ECR AWS Region (default "us-east-1")
    region: ""
    # -- Set the full hostname/url for the secret rather than building it with account and region
    host: ""
    # -- Docker ECR Password (required)
    # -- Command: aws ecr get-login-password
    password: ""
    # -- Should we run a post install/pre upgrade job to associate the ECR secret with the service account?
    patchDefaultServiceAccount: true


ingress:
  # -- The ingress class (set per ingress)
  # -- Options:
  # -- alb: (AWS Application Load balancer - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/)
  # -- nginx: Nginx Ingress (https://kubernetes.github.io/ingress-nginx/)
  enabled: true
  # -- Multiple hostnames can be provided if using external DNS, however this may not work for ingress-nginx
  hostname: "ligl-ui.dev.ezops.com.br"
  class: "nginx"
  # -- sslCertArn is only valid when using the 'alb' class. Leave empty for aut-select
  sslCertArn: ""
  # -- Uncomment below to add custom annotations for the public ingress
  annotations: {}
  alb:
    rules: []
    paths: []


application:
  image: "975635808270.dkr.ecr.us-east-2.amazonaws.com/reveal"
  tag: "monolith-service-master"
  name: "monolith-service-master"
  replicaCount: 2
  nodeSelector:
    kubernetes.io/os: windows
    kubernetes.io/arch: amd64
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2000Mi

configMap:
  name: "monolith-config" 
  # Connection strings
  DefaultConnectionString: "data source=10.0.0.8\\vertical_dev,58081;initial catalog=DEV_MIGRATION;integrated security=True;MultipleActiveResultSets=True;Enlist=false;App=EntityFramework"
  CaseCustodianDataSourceContextConnectionString: "data source=10.0.0.8\\vertical_dev,58081;initial catalog=DEV_MIGRATION;integrated security=True;multipleactiveresultsets=True;application name=EntityFramework"
  ProcessingEngineEntitiesConnectionString: "metadata=res://*/Master.Master.csdl|res://*/Master.Master.ssdl|res://*/Master.Master.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=10.0.0.8\\vertical_dev,58081;initial catalog=DEV_MASTER;integrated security=True;MultipleActiveResultSets=True;Enlist=false;App=EntityFramework&quot;"
  ReportManagementEntitiesConnectionString: "metadata=res://*/ProcessingEngineManagement.ProcessingEngine.csdl|res://*/ProcessingEngineManagement.ProcessingEngine.ssdl|res://*/ProcessingEngineManagement.ProcessingEngine.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=10.0.0.8\\vertical_dev,58081;initial catalog=DEV_MASTER;integrated security=True;MultipleActiveResultSets=True;Enlist=false;App=EntityFramework&quot;"
  EntityDbConnectionString: "metadata={0};provider=System.Data.SqlClient;provider connection string=&quot;data source={1};initial catalog={2};{3};MultipleActiveResultSets=True;Enlist={4};App=EntityFramework&quot;"
  StagingEntitiesConnectionString: "metadata=res://*/Staging.Staging.csdl|res://*/Staging.Staging.ssdl|res://*/Staging.Staging.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=10.0.0.8\\vertical_dev,58081;initial catalog=DEV_STAGING;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework&quot;"
  # App settings
  FileRepositoryLocation: FileRepository
  EmployeeImportTemplateLocation: EmployeeImportTemplates
  NonLegalHelpDocumentName: HelpDocument.pdf
  EncyKey: VDev@2016
  DocumentStoreLocation: Document_Store
  documentStore_path: http://localhost:10892/document_store/
  document_physical_path: ""
  WebUrl: http://localhost:13399/
  StaticUrl: http://localhost:15587/index.aspx
  LHExpiryTimeInHours: 48
  redisCache: localhost
  Log4NetConfigPath: log4net.config
  EventLogName: Application
  EventLogSource: Vertical-Log
  IsAsyncLoggingEnabled: true
  PrivateKey: password@123
  DefaultPasswordKey: VerticalPassword#123
  AccessTokenExpiryInMinutes: 60
  AccessControlAllowOrigin: "*"
  PluginUserFullName: pluginacc
  ImportRowsThreshold: 100
  AllowedFileTypesForImport: ".csv"
  PublishStackTrace: true
  ClientInstance: OptimumDevVerticalNas
  ClientDoamins: "vertical,in.vertical.com,verticaldiscovery.com,verticaldiscoverytest.onmicrosoft.com"
  useTaskFriendlySynchronizationContext: true
  ForgotPwdExpiryTimeInHours: 48
  Issuer: VerticalAuthority
  Audience: Everyone
  Secret: IxrAjDoa2FqEl3RIhrSrUJELhUckePEPVpaePlS_Poa
  IsAngularMigrated: true
  CCDInsertChunk: 100
  MaximumCCDInsertions: 1000
  ClientAppConfigDecryptKey: verticaldev@1234
  UIUrl: https://in-opt-dit-01.in.vertical.com/Dev_Angular/
  AntiVirusCheckerClamAV: false
