---
global:
  # K8s namespace. The name of the deployment.
  namespace: "monolith-service"


  ecr:
    enabled: false
    secret: "reveal-ecr"
    # -- AWS Account ID (default "475250404638")
    account: ""
    # -- ECR AWS Region (default "us-east-1")
    region: ""
    # -- Set the full hostname/url for the secret rather than building it with account and region
    host: ""
    # -- Docker ECR Password (required)
    # -- Command: aws ecr get-login-password
    password: ""
    # -- Should we run a post install/pre upgrade job to associate the ECR secret with the service account?
    patchDefaultServiceAccount: true


ingress:
  # -- The ingress class (set per ingress)
  # -- Options:
  # -- alb: (AWS Application Load balancer - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/)
  # -- nginx: Nginx Ingress (https://kubernetes.github.io/ingress-nginx/)
  enabled: true
  # -- Multiple hostnames can be provided if using external DNS, however this may not work for ingress-nginx
  hostname: "ligl-ui.dev.ezops.com.br"
  class: "nginx"
  # -- sslCertArn is only valid when using the 'alb' class. Leave empty for aut-select
  sslCertArn: ""
  # -- Uncomment below to add custom annotations for the public ingress
  annotations: {}
  alb:
    rules: []
    paths: []


application:
  image: "975635808270.dkr.ecr.us-east-2.amazonaws.com/reveal"
  tag: "monolith-service-master"
  name: "monolith-service-master"
  replicaCount: 2
  nodeSelector:
    kubernetes.io/os: windows
    kubernetes.io/arch: amd64
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2000Mi


secrets:
  enabled: false
  # -- The secrets provider
  # -- Providers:
  # --- external-secrets: (https://external-secrets.io/v0.5.9/)
  # --- kubernetes: Use kubernetes secret. Add secrets to the 'kubernetes' section below.
  provider: "external-secrets"

  # -- OPTIONS FOR: 'external-secrets' -- #
  externalSecrets:
    # -- The external-secrets provider
    # -- Providers:
    # --- aws: AWS SecretsManager
    provider: aws
    # -- Options for aws (AWS SecretsManager)
    aws:
      # -- Region: The AWS region where the secret resides (default "us-east-1")
      region: "us-east-2"
    enabled: true
    # Specifies whether a service account should be created
    create: true

    # Specifies the name of the kubernetes secrets
    name: "monolith-service-secrets"

    # Specifies the service account for external-secrets
    serviceAccount:
      name: "monolith-service-sa"
      arn: ""

  secretDefinitions:
    data:
      - name: DB_HOST
        key: prod/reveal
        property: DB_HOST
      - name: DB_PORT
        key: prod/reveal
        property: DB_PORT
      - name: DB_NAME
        key: prod/reveal
        property: DB_NAME
      - name: DB_USERNAME
        key: prod/reveal
        property: DB_USERNAME
      - name: DB_PASSWORD
        key: prod/reveal
        property: DB_PASSWORD



configMap:
  name: "monolith-config" 
  # Connection strings
  DefaultConnectionString: "data source=sql-server-backup-development.sql-server-backup.svc.cluster.local,1433;initial catalog=UAT_ENT_VEDB1;user id=sa;pwd=password123@;MultipleActiveResultSets=True;Enlist=false;App=EntityFramework"
  CaseCustodianDataSourceContextConnectionString: "data source=sql-server-backup-development.sql-server-backup.svc.cluster.local,1433;initial catalog=UAT_ENT_VEDB1;user id=sa;pwd=password123@;multipleactiveresultsets=True;application name=EntityFramework"
  MasterEntitiesConnectionString: "metadata=res://*/Master.Master.csdl|res://*/Master.Master.ssdl|res://*/Master.Master.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=source=sql-server-backup-development.sql-server-backup.svc.cluster.local,1433;initial catalog=UAT_ENT_VMDB;user id=sa;pwd=password123@;MultipleActiveResultSets=True;Enlist=false;App=EntityFramework&quot;"
  ProcessingEngineEntitiesConnectionString: "metadata=res://*/ProcessingEngineManagement.ProcessingEngine.csdl|res://*/ProcessingEngineManagement.ProcessingEngine.ssdl|res://*/ProcessingEngineManagement.ProcessingEngine.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=source=sql-server-backup-development.sql-server-backup.svc.cluster.local,1433;initial catalog=UAT_ENT_VMDB;user id=sa;pwd=password123@;MultipleActiveResultSets=True;Enlist=false;App=EntityFramework&quot;"
  ReportManagementEntitiesConnectionString: "metadata=res://*/ReportManagement.ReportManagement.csdl|res://*/ReportManagement.ReportManagement.ssdl|res://*/ReportManagement.ReportManagement.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=source=sql-server-backup-development.sql-server-backup.svc.cluster.local,1433;initial catalog=UAT_ENT_VRDB;user id=sa;pwd=password123@;MultipleActiveResultSets=True;Enlist=false;App=EntityFramework&quot;"
  EntityDbConnectionString: "metadata={0};provider=System.Data.SqlClient;provider connection string=&quot;data source={1};initial catalog={2};{3};MultipleActiveResultSets=True;Enlist={4};App=EntityFramework&quot;"
  StagingEntitiesConnectionString: "metadata=res://*/Staging.Staging.csdl|res://*/Staging.Staging.ssdl|res://*/Staging.Staging.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=source=sql-server-backup-development.sql-server-backup.svc.cluster.local,1433;initial catalog=UAT_ENT_VSDB;user id=sa;pwd=password123@;MultipleActiveResultSets=True;App=EntityFramework&quot;"
  # App settings
  FileRepositoryLocation: FileRepository
  EmployeeImportTemplateLocation: EmployeeImportTemplates
  NonLegalHelpDocumentName: HelpDocument.pdf
  EncyKey: VDev@2016
  DocumentStoreLocation: Document_Store
  documentStore_path: http://localhost:10892/document_store/
  document_physical_path: ""
  WebUrl: ligl-ui.dev.ezops.com.br
  StaticUrl: http://localhost:15587/index.aspx
  LHExpiryTimeInHours: 48
  redisCache: localhost
  Log4NetConfigPath: log4net.config
  EventLogName: Application
  EventLogSource: Vertical-Log
  IsAsyncLoggingEnabled: true
  PrivateKey: password@123
  DefaultPasswordKey: VerticalPassword#123
  AccessTokenExpiryInMinutes: 60
  AccessControlAllowOrigin: "*"
  PluginUserFullName: pluginacc
  ImportRowsThreshold: 100
  AllowedFileTypesForImport: ".csv"
  PublishStackTrace: true
  ClientInstance: OptimumDevVerticalNas
  ClientDoamins: "vertical,in.vertical.com,verticaldiscovery.com,verticaldiscoverytest.onmicrosoft.com"
  useTaskFriendlySynchronizationContext: true
  ForgotPwdExpiryTimeInHours: 48
  Issuer: VerticalAuthority
  Audience: Everyone
  Secret: IxrAjDoa2FqEl3RIhrSrUJELhUckePEPVpaePlS_Poa
  IsAngularMigrated: true
  CCDInsertChunk: 100
  MaximumCCDInsertions: 1000
  ClientAppConfigDecryptKey: verticaldev@1234
  UIUrl: ligl-ui.dev.ezops.com.br
  AntiVirusCheckerClamAV: false
