apiVersion: v1
kind: Service
metadata:
  name: service-authentication-service
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  
spec:
  selector:
    app: {{.Values.service.name }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443