apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
data: 
  appsettings.json: |-
  {{ .Values.configMap.configuration | toJson | indent 3 }}

