---
global:
  # K8s namespace. The name of the deployment.
  namespace: "ligl-ui"


  ecr:
    enabled: false
    secret: "reveal-ecr"
    # -- AWS Account ID (default "475250404638")
    account: ""
    # -- ECR AWS Region (default "us-east-1")
    region: ""
    # -- Set the full hostname/url for the secret rather than building it with account and region
    host: ""
    # -- Docker ECR Password (required)
    # -- Command: aws ecr get-login-password
    password: ""
    # -- Should we run a post install/pre upgrade job to associate the ECR secret with the service account?
    patchDefaultServiceAccount: true

application:
  image: "975635808270.dkr.ecr.us-east-2.amazonaws.com/reveal"
  tag: "new-tag"
  name: "ligl-ui"
  replicaCount: 2
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 1000Mi

ingress:
  # -- The ingress class (set per ingress)
  # -- Options:
  # -- alb: (AWS Application Load balancer - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/)
  # -- nginx: Nginx Ingress (https://kubernetes.github.io/ingress-nginx/)
  enabled: true
  # -- Multiple hostnames can be provided if using external DNS, however this may not work for ingress-nginx
  hostname: "ligl-ui.dev.ezops.com.br"
  class: "nginx"
  # -- sslCertArn is only valid when using the 'alb' class. Leave empty for aut-select
  sslCertArn: ""
  # -- Uncomment below to add custom annotations for the public ingress
  annotations: {}
  alb:
    rules: []
    paths: []

configMap:
  name: "ligl-ui-config" 
  configuration: |-
    {
      "serviceIp": "ligl-ui.dev.ezops.com.br/",
      "webSocketUrl": "ws://10.0.0.10:8092/",
      "loginUrl": "/Token",
      "getUserUrl": "/api/user",
      "oData": "/odata/",
      "moduleLookupUrl": "/odata/Modules",
      "appSettingUrl": "/odata/AppSettings",
      "oDataTaxonomyUrl": "/odata/TaxonomyService/",
      "userPermissions": "/odata/UserPermissions",
      "logoutUrl": "/api/ApplicationLogout",
      "telerikReportServerUrl": "http://localhost:17080",
      "apiPrefixURL": "/api/",
      "defaultLanguage": "en-us",
      "IsNuixEnvironment": false,
      "isCommonSpiritInstance": true,
      "isLocalization": true,
      "ClientName": "Reveal-Brainspace",
      "AuthenticationProviderType": "BasicAuthentication",
      "IsSSOSPInitiatedEnabled": true,
      "IsMearsk": true,
      "ssoSPInitiatedUrl": "https://myapps.microsoft.com/signin/SSOTEST/c901be31-6b06-400f-befd-c1e4fc855a43?tenantId=0b72188d-58bf-4491-880a-49e3f402721d",
      "ApproversCount": 2,
      "DocumentHelpUrl": "https://unec.edu.az/application/uploads/2014/12/pdf-sample.pdf",
      "telerikReportServerUrlNew": "https://in-opt-sit-01.in.vertical.com:44399/",
      "reviewUrl": "https://landing.revealdata.com/",
      "scheduledtasksUrl": "https://telerik.myligl.io/api/reportserver/v2/scheduledtasks",
      "reportParameters": "https://telerik.myligl.io/api/reportserver/v2/reports/{reportID}/parameters",
      "clientID": "https://telerik.myligl.io/api/reports/clients",
      "reportParametersByClientID": "https://telerik.myligl.io/api/reports/clients/{clientId}/parameters",
      "telerikToken": "https://telerik.myligl.io/token",
      "childParameters": "https://telerik.myligl.io/api/reports/clients/{clientId}/parameters",
      "getScheduledTask": "https://telerik.myligl.io/api/reportserver/v2/scheduledtasks"
    }

secrets:
  # -- The secrets provider
  # -- Providers:
  # --- external-secrets: (https://external-secrets.io/v0.5.9/)
  # --- kubernetes: Use kubernetes secret. Add secrets to the 'kubernetes' section below.
  provider: "external-secrets"

  # -- OPTIONS FOR: 'external-secrets' -- #
  externalSecrets:
    # -- The external-secrets provider
    # -- Providers:
    # --- aws: AWS SecretsManager
    provider: aws
    # -- Options for aws (AWS SecretsManager)
    aws:
      # -- Region: The AWS region where the secret resides (default "us-east-1")
      region: "us-east-2"
    enabled: true
    # Specifies whether a service account should be created
    create: true

    # Specifies the name of the kubernetes secrets
    name: "ligl-ui-secrets"

    # Specifies the service account for external-secrets
    serviceAccount:
      name: "ligl-ui-sa"
      arn: "arn:aws:iam::975635808270:role/ligl-ui-us-east-2-eks-secrets-role-irsa"

  secretDefinitions:
    data:
      - name: LOGIN_URL
        key: prod/reveal/ligl-ui
        property: LOGIN_URL
      - name: GET_USER_URL
        key: prod/reveal/ligl-ui
        property: GET_USER_URL
      - name: ODATA
        key: prod/reveal/ligl-ui
        property: ODATA
      - name: MODULE_LOOKUP_URL
        key: prod/reveal/ligl-ui
        property: MODULE_LOOKUP_URL
      - name: APP_SETTING_URL
        key: prod/reveal/ligl-ui
        property: APP_SETTING_URL
      - name: ODATA_TAXONOMY_URL
        key: prod/reveal/ligl-ui
        property: ODATA_TAXONOMY_URL
      - name: USER_PERMISSIONS
        key: prod/reveal/ligl-ui
        property: USER_PERMISSIONS
      - name: LOGOUT_URL
        key: prod/reveal/ligl-ui
        property: LOGOUT_URL
      - name: API_PREFIX_URL
        key: prod/reveal/ligl-ui
        property: API_PREFIX_URL