---
- name: Create AWS S3 Bucket
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Include AWS credentials
      include_vars:
        file: aws_credentials.yml

    - name: Create S3 Bucket
      s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ s3_bucket_name }}"
        state: present