global:
  env: development
  helmDefault: false
  valuesFile: values.yaml
  spec:
    project: devops
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd-system
    source:
      repoURL: git@github.com:ArthurMaverick/devops_project.git
      targetRevision: HEAD

argocdApplications:
  app:
    disableAutomated: false
    disable: false
    name: python-app
    path: dev/us-east-1/services/apps/api-02/helm
    namespace: python-app
    #    targetRevision: HEAD
    helm: true
