replicaCount: 1
image:
  repository: 716716811630.dkr.ecr.us-east-1.amazonaws.com/devops-default-python-app
  tag: '3b5fac462d21ca164b3778647420016315289034'
nameOverride: ''
fullnameOverride: ''
service:
  type: ClusterIP
  port: 9555
