
replicaCount: 1

image:
  repository: 716716811630.dkr.ecr.us-east-1.amazonaws.com/devops-default-python-app
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9555
