apiVersion: v1
kind: Service
metadata:
  name: service-ligl-external
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  
spec:
  selector:
    app: deployment-ligl-external
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80