apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
data: 
  configuration.json: |-
    {
      "serviceIp": "{{ .Values.configMap.serviceIp }}",
      "IsNuixEnvironment": {{ .Values.configMap.IsNuixEnvironment }},
      "UserLHNSignature": "{{ .Values.configMap.UserLHNSignature }}",
      "UserLHNCurrentStatus": "{{ .Values.configMap.UserLHNCurrentStatus }}",
      "IsSSOEnabledForLHNAcknowledgement": "{{ .Values.configMap.IsSSOEnabledForLHNAcknowledgement }}",
      "LiglUILoginURL": "{{ .Values.configMap.LiglUILoginURL }}",
      "IsLHNTitleMandatory": "{{ .Values.configMap.IsLHNTitleMandatory }}"
    }



