apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd-system
spec:
  destination:
    namespace: python-app
    server: "https://kubernetes.default.svc"
  source:
    path: "dev/us-east-1/services/apps/api-01/helm"
    repoURL: "git@github.com:ArthurMaverick/devops_project.git"
    targetRevision: "HEAD"
    helm:
      valueFiles:
        - "values.yaml"
  project: "devops"
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        managed: "argo-cd"
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true