apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
    - host: "api.santosops.com"
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 9555
            pathType: "Prefix"
            path: "/"
  tls:
    - hosts:
        - "api.santosops.com"
      secretName: "santos-ops"