apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Release.Name }}
  selector:
    app.kubernetes.io/name: python-app
