---
global:
  # K8s namespace. The name of the deployment.
  namespace: "sql-server-backup"

fullnameOverride: "sql-server-backup"
acceptEula:
  value: "n"
edition:
  value: Express 
collation: SQL_Latin1_General_CP1_CI_AS
dataDir: /var/opt/mssql
lcid: 1033
hadr: 0
replicaCount: 1
# Override sapassword in templates/secret.yaml
sapassword: "PASSWORD123456789@"
image:
  repository: 975635808270.dkr.ecr.us-east-2.amazonaws.com/reveal
  tag: sql-server-backup
  pullPolicy: IfNotPresent
  

service:
  # If headless is set to TRUE then the service type is ignored
  headless: false
  type: ClusterIP
  port: 1433
  annotations: {}
  labels: {}
deployment:
  annotations: {}
  labels: {}
pod:
  annotations: {}
  labels: {}
persistence:
  enabled: true
  # existingDataClaim:
  storageClass: ""
  dataAccessMode: ReadWriteOnce
  dataSize: 1Gi
livenessprobe:
  initialDelaySeconds: 15
  periodSeconds: 20
readinessprobe:
  initialDelaySeconds: 5
  periodSeconds: 10
resources:
  limits:
  #  cpu: 100m
    memory: 2Gi
  # requests:
  #  cpu: 100m
  #  memory: 2Gi
nodeSelector: {}
  # kubernetes.io/hostname: microk8s
