apiVersion: v1
kind: Service
metadata:
  name: service-taxonomy-service
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  
spec:
  selector:
    app: deployment-taxonomy-service
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80