apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.loki.name }}
  namespace: {{ .Values.global.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.loki.destination.namespace }}
    server: {{ .Values.loki.destination.server }}
  source:
    path: {{ .Values.loki.path }}
    repoURL: {{ .Values.loki.repoURL }}
    targetRevision: {{ .Values.loki.targetRevision }}
    helm:
      valueFiles:
        - "values.yaml"
  project: "devops"
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        managed: "argo-cd"
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2